### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by nvattai** [Coinnect-SA/CybGPT#8]
scan.js ip parameter not sanitized with zod @aryan-c02 :   
```

if (isValidIP(ip)) {
    try {
      const response = await axios({
        url: `${config.ip_feed}/cyb/scanIP/${ip}`,
        method: 'get',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json'
        }
      })
```

**Comment by aryan-c02** [comment]
hi @nvattai  can i use external module like https://www.npmjs.com/package/ip-address. Its difficult to validate ip address using zod it might leave some edge cases.

**Comment by nvattai** [comment]
@aryan-c02 you might be overthinking the issue. It does not work like [this](https://zod.dev/?id=ip-addresses)?

**Comment by aryan-c02** [comment]
Thanks for pointing it out . I have created pull request with optimized code.
